name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Jekyll
        run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './site'
      - uses: actions/deploy-pages@v4
